#!/bin/sh
python test_mln.py --query_role class                --input_mln ./models/class_learned.mln                --positive_database ./data/class_test.db                --positive_dataset ./data/test_data.txt --negative_dataset ./data/test_data_negative.txt
python test_mln.py --query_role color                --input_mln ./models/color_learned.mln                --positive_database ./data/color_test.db                --positive_dataset ./data/test_data.txt --negative_dataset ./data/test_data_negative.txt
python test_mln.py --query_role dimension            --input_mln ./models/dimension_learned.mln            --positive_database ./data/dimension_test.db            --positive_dataset ./data/test_data.txt --negative_dataset ./data/test_data_negative.txt
python test_mln.py --query_role purity               --input_mln ./models/purity_learned.mln               --positive_database ./data/purity_test.db               --positive_dataset ./data/test_data.txt --negative_dataset ./data/test_data_negative.txt
python test_mln.py --query_role dampness             --input_mln ./models/dampness_learned.mln             --positive_database ./data/dampness_test.db             --positive_dataset ./data/test_data.txt --negative_dataset ./data/test_data_negative.txt
python test_mln.py --query_role room                 --input_mln ./models/room_learned.mln                 --positive_database ./data/room_test.db                 --positive_dataset ./data/test_data.txt --negative_dataset ./data/test_data_negative.txt
python test_mln.py --query_role temperature          --input_mln ./models/temperature_learned.mln          --positive_database ./data/temperature_test.db          --positive_dataset ./data/test_data.txt --negative_dataset ./data/test_data_negative.txt
python test_mln.py --query_role price                --input_mln ./models/price_learned.mln                --positive_database ./data/price_test.db                --positive_dataset ./data/test_data.txt --negative_dataset ./data/test_data_negative.txt
python test_mln.py --query_role material             --input_mln ./models/material_learned.mln             --positive_database ./data/material_test.db             --positive_dataset ./data/test_data.txt --negative_dataset ./data/test_data_negative.txt
python test_mln.py --query_role weight               --input_mln ./models/weight_learned.mln               --positive_database ./data/weight_test.db               --positive_dataset ./data/test_data.txt --negative_dataset ./data/test_data_negative.txt
python test_mln.py --query_role physical_property    --input_mln ./models/physical_property_learned.mln    --positive_database ./data/physical_property_test.db    --positive_dataset ./data/test_data.txt --negative_dataset ./data/test_data_negative.txt
python test_mln.py --query_role shape                --input_mln ./models/shape_learned.mln                --positive_database ./data/shape_test.db                --positive_dataset ./data/test_data.txt --negative_dataset ./data/test_data_negative.txt
python test_mln.py --query_role specific_place       --input_mln ./models/specific_place_learned.mln       --positive_database ./data/specific_place_test.db       --positive_dataset ./data/test_data.txt --negative_dataset ./data/test_data_negative.txt
python test_mln.py --query_role transparency         --input_mln ./models/transparency_learned.mln         --positive_database ./data/transparency_test.db         --positive_dataset ./data/test_data.txt --negative_dataset ./data/test_data_negative.txt
python test_mln.py --query_role size                 --input_mln ./models/size_learned.mln                 --positive_database ./data/size_test.db                 --positive_dataset ./data/test_data.txt --negative_dataset ./data/test_data_negative.txt
python test_mln.py --query_role spatial_distribution --input_mln ./models/spatial_distribution_learned.mln --positive_database ./data/spatial_distribution_test.db --positive_dataset ./data/test_data.txt --negative_dataset ./data/test_data_negative.txt
