#!/bin/sh
python test_mln.py --query_role class                --input_mln ./models/class_learned.mln                --positive_database ./data/class_valid.db                --positive_dataset ./data/val_data.txt --negative_dataset ./data/val_data_negative.txt
python test_mln.py --query_role color                --input_mln ./models/color_learned.mln                --positive_database ./data/color_valid.db                --positive_dataset ./data/val_data.txt --negative_dataset ./data/val_data_negative.txt
python test_mln.py --query_role dimension            --input_mln ./models/dimension_learned.mln            --positive_database ./data/dimension_valid.db            --positive_dataset ./data/val_data.txt --negative_dataset ./data/val_data_negative.txt
python test_mln.py --query_role purity               --input_mln ./models/purity_learned.mln               --positive_database ./data/purity_valid.db               --positive_dataset ./data/val_data.txt --negative_dataset ./data/val_data_negative.txt
python test_mln.py --query_role dampness             --input_mln ./models/dampness_learned.mln             --positive_database ./data/dampness_valid.db             --positive_dataset ./data/val_data.txt --negative_dataset ./data/val_data_negative.txt
python test_mln.py --query_role room                 --input_mln ./models/room_learned.mln                 --positive_database ./data/room_valid.db                 --positive_dataset ./data/val_data.txt --negative_dataset ./data/val_data_negative.txt
python test_mln.py --query_role temperature          --input_mln ./models/temperature_learned.mln          --positive_database ./data/temperature_valid.db          --positive_dataset ./data/val_data.txt --negative_dataset ./data/val_data_negative.txt
python test_mln.py --query_role price                --input_mln ./models/price_learned.mln                --positive_database ./data/price_valid.db                --positive_dataset ./data/val_data.txt --negative_dataset ./data/val_data_negative.txt
python test_mln.py --query_role material             --input_mln ./models/material_learned.mln             --positive_database ./data/material_valid.db             --positive_dataset ./data/val_data.txt --negative_dataset ./data/val_data_negative.txt
python test_mln.py --query_role weight               --input_mln ./models/weight_learned.mln               --positive_database ./data/weight_valid.db               --positive_dataset ./data/val_data.txt --negative_dataset ./data/val_data_negative.txt
python test_mln.py --query_role physical_property    --input_mln ./models/physical_property_learned.mln    --positive_database ./data/physical_property_valid.db    --positive_dataset ./data/val_data.txt --negative_dataset ./data/val_data_negative.txt
python test_mln.py --query_role shape                --input_mln ./models/shape_learned.mln                --positive_database ./data/shape_valid.db                --positive_dataset ./data/val_data.txt --negative_dataset ./data/val_data_negative.txt
python test_mln.py --query_role specific_place       --input_mln ./models/specific_place_learned.mln       --positive_database ./data/specific_place_valid.db       --positive_dataset ./data/val_data.txt --negative_dataset ./data/val_data_negative.txt
python test_mln.py --query_role transparency         --input_mln ./models/transparency_learned.mln         --positive_database ./data/transparency_valid.db         --positive_dataset ./data/val_data.txt --negative_dataset ./data/val_data_negative.txt
python test_mln.py --query_role size                 --input_mln ./models/size_learned.mln                 --positive_database ./data/size_valid.db                 --positive_dataset ./data/val_data.txt --negative_dataset ./data/val_data_negative.txt
python test_mln.py --query_role spatial_distribution --input_mln ./models/spatial_distribution_learned.mln --positive_database ./data/spatial_distribution_valid.db --positive_dataset ./data/val_data.txt --negative_dataset ./data/val_data_negative.txt
